language: perl
perl:
  - "5.8.4"
  - "5.8.4_thr"
before_install:
  - source maint/travis-perlbrew
  - perlbrew install-cpanm -f
  - perl -V
install:
  - cpanm --verbose --no-interactive --notest strictures autodie
  - cpanm --verbose --no-interactive --notest --installdeps --with-develop --with-recommends --with-suggests .
  - cpanm --verbose --no-interactive --notest Devel::Cover::Report::Coveralls
script:
  - maint/fulltest --cover
after_success:
  - cover -report coveralls
notifications:
  email: false
  on_success: change
  on_failure: change
