language: perl
perl:
  - "5.18"
  - "5.12.5"
  - "5.8.4"
  - "5.8.4_thr"
before_install:
  - source maint/travis-perlbrew
  - perlbrew install-cpanm -f
  - perl -V
install:
  - cpanm --verbose --no-interactive --no-man-pages --notest strictures ExtUtils::MakeMaker
  - cpanm --verbose --no-interactive --no-man-pages --notest --installdeps --with-develop --with-recommends --with-suggests .
script:
  - maint/fulltest
branches:
  except:
    - /^wip\//
    - /^blocked/
notifications:
  email: false
  on_success: change
  on_failure: change
