language: perl
perl:
  - "5.19"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
before_install:
  - perlbrew install-cpanm -f
  - perl -V
install:
  - cpanm -nq strictures
  - cpanm -nq --installdeps --with-develop --with-recommends --with-suggests .
  - cpanm -nq Devel::Cover::Report::Coveralls
script:
  - maint/fulltest --cover
after_success:
  - cover -report coveralls
notifications:
  email: false
  on_success: change
  on_failure: change
