language: perl
perl:
  - "5.8.4"
  - "5.8.4_thr"
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
matrix:
  include:
    - perl: 5.8.1
      env: AUTHOR_TESTING=0
    - perl: 5.18
      env: COVERAGE=1
before_install:
  - source maint/travis-perlbrew
  - perlbrew install-cpanm -f
  - perl -V
install:
  - maint/travis-install ExtUtils::MakeMaker strictures
  - maint/travis-install --deps
  - "[ -n \"$COVERAGE\" ] && maint/travis-install Devel::Cover Devel::Cover::Report::Coveralls || true"
script:
  - maint/fulltest
after_success:
  - "[ -n \"$COVERAGE\" ] && cover -report coveralls || true"
branches:
  except:
    - /^wip\//
    - /^blocked/
notifications:
  email: false
  on_success: change
  on_failure: change
